-- Retrieve the total number of rentals made in the Sakila database.
use sakila;
select count(*) as count_rental
from rental;

-- Find the average rental duration (in days) of movies rented from the Sakila database.
select avg(rental_duration) as Average_duration
from film;

-- Display the first name and last name of customers in uppercase.
select upper(first_name) as first_name, upper(last_name) as last_name
from customer;

-- Extract the month from the rental date and display it alongside the rental ID.
select rental_id, month(rental_date) as Months
from rental;

-- Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
select customer_id, count(rental_id) as rental
from rental
Group by customer_id;

-- Find the total revenue generated by each store.
select staff_id, sum(amount) as Total_revenue
from payment
group by staff_id;

-- Display the title of the movie, customer s first name, and last name who rented it.
select f.title, c.first_name, c.last_name
from customer c
join rental r
on c.customer_id = r.customer_id
join inventory i
on r.inventory_id = i.inventory_id
join film f
on i.film_id = f.film_id;

-- Retrieve the names of all actors who have appeared in the film "Gone Trouble"
select a.first_name, last_name
from actor a
join film_actor fa
on a.actor_id = fa.actor_id
join film f
on fa.film_id = f.film_id
where f.title = "Gone Trouble";

-- Determine the total number of rentals for each category of movies.
select fc.category_id,f. rating, count(rental_id) as no_of_rentals
from film_category fc
join film f
on fc.film_id = f.film_id
join rental r
on r.rental_id = f.film_id
group by category_id;

-- Find the average rental rate of movies in each language.
select l.name, avg(f.rental_rate) as avg_rental_rate
from language l
join film f
on l.language_id = f.film_id
group by l.name;

-- Retrieve the customer names along with the total amount they've spent on rentals.
select concat(c.first_name,' ', c.last_name) as name, sum(p.amount) as total_amount
from customer c
join rental r
on c.customer_id = r.customer_id
join payment p
on p.rental_id = r.rental_id
group by name;

-- List the titles of movies rented by each customer in a particular city (e.g., 'London').
select f.title, concat(c.first_name, ' ', c.last_name) as name, ci.city
from customer c
join film f
on f.film_id = c.customer_id
join address a
on c.address_id = a.address_id
join city ci
on ci.city_id = a.city_id
group by ci.city;

-- Display the top 5 rented movies along with the number of times they've been rented.
select f.title, count(r.rental_id) as count_rental
from film f
join inventory i
on f.film_id = i.film_id
join rental r
on r.inventory_id = i.inventory_id
group by f.title
order by count_rental desc limit 5;

-- Determine the customers who have rented movies from both stores (store ID 1 and store ID 2).
select Distinct concat(c.first_name, ' ', c.last_name) as name, count(c.store_id) as store
from customer c
join rental r
on r.customer_id = c.customer_id
join inventory i
on i.inventory_id = r.inventory_id
group by name;